version: '3'
services:
  db:
    image: mariadb:10.2
    container_name: db-drupal
    environment:
      MYSQL_DATABASE: "drupal"
      MYSQL_ROOT_PASSWORD: "Drupal"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - drupal_db_net
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
    links:
      - db:db
    restart: always
    networks:
      - drupal_db_net

volumes:
  db_data:

networks:
  drupal_db_net:
    driver: bridge